debug: true
trace: true
logtime: true

# Listen on all interfaces (0.0.0.0) or specify your IP
host: "0.0.0.0"
port: 4222

accounts {
    SYS {
        users = [
            { user: "admin", password: "password" }
        ]
    }
}

system_account: SYS

